Fixed a typo in ariane_tb.cpp
The old line causes the following compilation problem:
 ../tb/ariane_tb.cpp:323:50: error: no member named 'ariane_testharness__DOT__i_sram__DOT__genblk1__BRA__0__KET____DOT__genblk2__DOT__i_ram__DOT__Mem_DP' in 'Variane_testharness'; did you mean 'ariane_testharness__DOT__i_sram__DOT__genblk1__BRA__0__KET____DOT__genblk1__DOT__i_ram__DOT__Mem_DP'?